name: Deploy to SFTP
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MAVEN_VERSION: ${{ steps.extract_version.outputs.maven_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package
      - name: Extract Maven Version
        id: extract_version
        run: echo "::set-output name=maven_version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
      - name: Deploy to SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SERVER }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local_path: './target/ArenaPvp-${{ env.MAVEN_VERSION }}.jar'
          remote_path: '/plugins/'
          sftp_only: true
